### ISSUE TITLE
Could You please provide a license?

### ISSUE THREAD

**Issue by kcpr** [Emano-Waldeck/Save-Tabs#13]
Hi,

I would like to know if I can officially fork the repository and make some improvements. Could You please provide a license? Maybe just a [MIT](https://mit-license.org/) one?
Otherwise it seems that "all right are reserved" and no one can really modify the code: https://opensource.stackexchange.com/a/1721/27698 .

And thank You for the extension, sharing the code and all!

**Comment by Emano-Waldeck** [comment]
Done!
