### ISSUE TITLE
Does not save a high number of tabs

### ISSUE THREAD

**Issue by koppor** [Emano-Waldeck/Save-Tabs#16]
I click on "Save current window tabs"

![image](https://github.com/user-attachments/assets/fd606a52-57e2-4dff-b754-73b90aaacdbd)

I input some data

![image](https://github.com/user-attachments/assets/50c84bf6-d5af-481d-b643-aedb612b65b5)

I press "Save"

No new session created.

![image](https://github.com/user-attachments/assets/14be1e61-b5f9-499a-a73d-136b9c4df018)

---

If I chose "Save and close current window tabs", the window is closed, but no saved session is created.

**Comment by Emano-Waldeck** [comment]
Thank you for the report. Previously, the extension saved sessions in synced storage, but for larger sessions, it exceeded the maximum allowed size. Starting with the next release, the extension will switch to local storage when this occurs.
