### ISSUE TITLE
Simple request 01: Option to open tabs as unloaded/inactivated

### ISSUE THREAD

**Issue by EstherMoellman** [Emano-Waldeck/Save-Tabs#2]
Hi @Emano-Waldeck ,

Firstly, thank you very much for Save-Tabs.
On my first tests it seems to work pretty nice, and it's amazing the low browser performance impact, very lightweight! Congrats!

I have few simple requests, and this is my first one: Please add an option to open tabs as unloaded/inactivated.

Thank you in advance!

**Comment by EstherMoellman** [comment]
Hi @Emano-Waldeck ! Thank you so much for attending my requests so quickly... thank you from the bottom of my heart for your time and dedication.

I don't know what was your original intention for building SaveTabs. But personally, I would like to use SaveTabs as a tab-groups-manager add-on (I treat every session as a group of tabs).
Yeah, there are plenty of similar add-ons related to tabs management. But your add-on SaveTabs is the most lightweight (just 400KB RAM, with very low CPU use)... and believe me, I tested all kind of tab manager add-ons. Also, I prefer your add-on because it closes tabs instead of hiding/discarding tabs. Closing tabs is better for performance, privacy, security, and it avoids conflicts with other add-ons.
So, that's the reason yesterday I did my requests to you, because I want your SaveTabs as my tab manager add-on.

Today I updated your add-on, and I saw the "Discarded State". Please, allow me few questions:

1) When a session is restored with "Discarded State" checked, tabs are loaded for a couple of seconds, and then tabs are discarded. Instead loading and discarding, please, is it possible to restore a session directly with tabs totally unloaded/inactive? I have lot of saved sessions (for me sessions are "groups") with hundreds of tabs, so the ideal will be to restore a session/group with all the tabs inactive/unloaded.

2) When a session is restored with "Discarded State" checked, tab labels appear with "undefined". Please, is it possible to keep original tab labels with they original titles? And please, is it possible to keep the tab favicon? I believe that the original tab label is necessary, otherwise the "undefined" label defeats the inactive/unloaded purpose, because the user will need to click every tab one by one, in order to see his tabs. And in real life, if you have a session/group with 200 tabs, it'll be unpractical to click every tab in order to find a specific tab.

3) The current "Discarded State" needs to be checked every time the user wants to restore a session/group. But for example in my case, I would like to restore every session/group always with all tabs unloaded/inactive. So for me, checking the "Discarded State" every time, is uncomfortable. I would like this as my default behavior, always opening tabs in unloaded/inactive mode. So please, is it possible for SaveTabs to remember my choice ("Discarded State" checked) until I uncheck it?

Please @Emano-Waldeck , count on me if I can help you!
I have no programming know-how. But if you want, I can test your updates, upgrades, new features etc.

Zillions of thanks in advance! : )

**Comment by Emano-Waldeck** [comment]
> just 400KB RAM, with very low CPU use

Unfortunately, FF does not support nonpersistent background pages yet. On Chrome when the extension popup is closed, the usage is zero since the extension is in the idle state.

>  I tested all kind of tab manager add-ons

Also, give auto-tab-discard a try. You may find it useful in combination with another tab manager extension.

> Closing tabs is better for performance, privacy, security

For sure closing is the best option performance-wise. However, if a tab is thoroughly discarded, there is no JS execution going on, so it is safe privacy- and security-wise but still uses memory.

> tabs are loaded for a couple of seconds, and then tabs are discarded

True, when discarding is checked, instead of the actual tab, a minimal HTML is loaded, which loads the actual tab when visibility state changes. It is the lightest possible solution as far as I know (even lighter than native discarding which still uses browser's memory). Note that it is not possible to natively open a tab in the discarded state. There is no such API available.

There is one issue with the current method of discarding. These discarded pages are internal pages (moz-extension://...) which means that FF does not keep track of them in case your browser crashes.

> tab labels appear with "undefined"

The extension does not have the titles database yet. Will get fixed when you are storing new sessions.

> The current "Discarded State" needs to be checked every time

Fixed!

**Comment by EstherMoellman** [comment]
> Unfortunately, FF does not support nonpersistent background pages yet. On Chrome when the extension popup is closed, the usage is zero since the extension is in the idle state.

@Emano-Waldeck , SaveTabs (ST) at 400KB is already AMAZING good! Congrats!
And the point here is not exactly the amount of RAM (nowadays RAM is cheap and abundant). From my ignorance, ST' strengths are inside the tiny/lightweight code you beautifully wrote (just 45.53KB). It's a kind of fantastic the number of functions ST has with its current tiny script, so powerful, so efficient! And again, I can confirm that, because I tested 99% of all tab manager/session saver add-ons.
Session manager add-ons generally have small scripts, but they are too primitive, too basic, almost unfriendly to use. Your ST add-on is minimalist, but powerful, and very friendly to use.
Also is good to mention that not always but generally, a small efficient script means better browser performance, less conflicts with other add-ons or with the browser itself.

> Also, give auto-tab-discard a try. You may find it useful in combination with another tab manager extension.

Yeah, I know auto-tab-discard (Richard Neomy). But for ST I prefer "bookmarking/closing" functions instead of "hiding/discarding". And I prefer this "bookmarking/closing" functions inside ST (not depending on other add-ons).
ST as a session manager is already perfectly fine with the current "Discarded State" you built yesterday (thank you again!).
But I'm pushing ST to the next level... moving from session manager level to tab manager level, conceptually using "groups" instead of "sessions"... and in my ignorant opinion, as a tab manager add-on ST needs the "bookmarking/closing" function + restoring groups with "unloaded/inactive" tabs.
Of course, if you want to keep ST just as a session manager, I always will respect your decision! Your house, your rules! But honestly, ST is already so powerful and efficient, that the inclusion of few simple functions easily can convert ST into a Tab Manager add-on. By the way, the great work you did yesterday with my requests, now will demand you to rewrite your ST AMO' page, in order to list/describe the new powerful functions you built. And my guess is that users will perceive your ST not just as a session manager, but as Tab Groups Manager.

> However, if a tab is thoroughly discarded, there is no JS execution going on, so it is safe privacy- and security-wise but still uses memory.

I tested most of the tab manager add-ons for long periods. And my conclusion is: In real world, "bookmarking/closing" is much better than "hiding/discarding". I do recognize that "hiding/discarding" functions are fancy, convenient etc, users love them. But tab manager add-ons using "hiding/discarding", even with small scripts, they tend to have negative impact on browser performance, also creating conflicts with other add-ons and with the browser itself. Not to mention that "hiding/discarding" functions have lot of bugs, demanding lot of maintenance work from Dev's perspective.

> True, when discarding is checked, instead of the actual tab, a minimal HTML is loaded, which loads the actual tab when visibility state changes. It is the lightest possible solution as far as I know (even lighter than native discarding which still uses browser's memory). Note that it is not possible to natively open a tab in the discarded state. There is no such API available.

Sadly I don't have JS or programming know-how, so I can't tell you which code to write or which API to use.
As an ignorant user I only can tell you that most of the tab manager add-ons have this "unloaded/inactive" function I requested to you. I have no idea how they built that, but at these add-ons when a session/group is restored, tabs appear totally unloaded/inactive. If you're curious/interested, as an example the "Tabs To Bookmark Groups" (TTBG) is an excellent add-on, using bothe, the "bookmarking/closing" functions and the "unloaded/inactive" function (I'm not posting the url, in order to avoid references. But you can easily find this add-on at AMO).
This TTBG add-on has most of the features I requested you. I actively collaborated with the Dev (amazing nice guy) in the creation process. IMO TTBG is an outstanding add-on, but it is still in "alpha stage" (experimental), so currently it's 3x bigger than your ST, 2x RAM consuming, and it needs several improvements with some features. That's the reason I contacted you here, hoping your ST can fulfill "the last mile" where TTBG stopped/paused. Anyway, if you want, please, take a look at TTBG' script, it's an open source, and perhaps you can take from there some ideas to implement the "unloaded/inactive" function (instead of "Discarded State").

> There is one issue with the current method of discarding. These discarded pages are internal pages (moz-extension://...) which means that FF does not keep track of them in case your browser crashes.

Yeap! I'm aware about that, the same happens at TTBG... and I don't care at all.
Only add-ons using the "hiding" function can save "moz-pages". But for me and as I said, "bookmarking/closing" is unbeatable. And I don't mind to lose "moz-pages" at every session/group recovered.

> The extension does not have the titles database yet. Will get fixed when you are storing new sessions.

Totally my bad. I apologize. I can see now this perfectly working with new sessions. Thank you!
Any chance in the future to show tab favicons when tabs are "unloaded/inactive"?

> > The current "Discarded State" needs to be checked every time
> 
> Fixed!

Great! Thank you.

Again @Emano-Waldeck , amazing job you're doing. Congrats and thank you once again! : )

**Comment by Emano-Waldeck** [comment]
> now will demand you to rewrite your ST AMO' page

Would you like to help writing the new AMO page description? If so please attach the new description in a text file format and I'll publish it after the next release.

> most of the tab manager add-ons have this "unloaded/inactive" function I requested to you 

Okay seems like FF supports opening tabs in the discarded state which is weird considering it is not a standard API. Anyhow, from the next release, this extension opens tabs in native discarding state in FF. Thanks!

**Comment by EstherMoellman** [comment]
Hi @Emano-Waldeck , I'll be more than happy to help writing the new AMO' page. But:

1) My English is not good enough. So before publishing, please do the necessary grammar/syntax corrections.

2) I wrote a first model of text, not based on your current SaveTabs' add-on, but based on the vision of what SaveTabs can be transformed (by adding few simple features). I also took the liberty of changing the name of the add-on (TOP ORGANIZER) in order to allow users to understand that this is the most efficient tab groups manager add-on, not just a basic session manager.

3) If you still want to keep the current name (SaveTabs) and its basic function as a session manager, I totally will respect that! And in this case, we can delete some parts of the text I'm attaching you here, adapting the description to your specific definitions.

@Emano-Waldeck , you have nothing to thank me for!
As I mentioned in previous messages, I see your add-on with all the potential to become the best tab manager add-on out-there, at least in terms of browser performance, privacy and security. It just need few additional simple features and a small polishing. And this depends totally on you, your time, your work etc. So is me who thanks you in advance! It's amazing how fast you attended my requests. And if by chance you're willing to finish the rest of the work, then I'll be fully benefited from your fantastic work, because I'll have the perfect tab manager I need. And believe me, tab management in my case is critical for my work and studies: Everyday I need to have easy and intelligent access to more than 100 tab groups, containing more than 5000 tabs. So your add-on will save me tons of hours, without killing my browser performance, privacy, security etc. And I'm not alone here, I'm part of a big group of users with exactly the same needs. So your add-on will be a savior for us! Again, thank you indeed, and always keep counting with my help! : )

[Here is the first text model](https://pastebin.com/Y7utxkuu).

**Comment by EstherMoellman** [comment]
@Emano-Waldeck , the "unloaded" function seems to work like a charm! Congrats! It's exactly as I wanted. Thank you! : )
