### ISSUE TITLE
Simple request 03: Option to include/exclude pinned tabs in a session

### ISSUE THREAD

**Issue by EstherMoellman** [Emano-Waldeck/Save-Tabs#4]
@Emano-Waldeck , my third simple request: Please add an option to include/exclude pinned tabs in a session.

Thank you in advance!

**Comment by EstherMoellman** [comment]
I apologies in advance for my question: Have you included the option in the version 0.1.4? I can see pinned tabs are saved in a session (and this is great!). But what about the "exclude option"? This "exclude option" will be very useful when a tab is playing a movie, music, or for tabs having email accounts logged etc. So these pinned tabs normally users don't want to close. Then, when users change session/groups, they want always to keep these pinned tabs visible/opened. And for that, the "exclude option" is needed.

**Comment by Emano-Waldeck** [comment]
> But what about the "exclude option"

There is a new option in the save dialog which can include or exclude pinned tabs. If you are using the silent mode, uncheck it once and adjust the settings and then check it back.
