### ISSUE TITLE
Simple request 04: Convert sessions in bookmarks

### ISSUE THREAD

**Issue by EstherMoellman** [Emano-Waldeck/Save-Tabs#5]
@Emano-Waldeck , my fourth simple request: Please convert sessions in bookmarks, so users will be able to edit sessions (copy, paste, delete, import, export etc) in the same way users edit bookmarks.

Thank you in advance!

**Comment by EstherMoellman** [comment]
This is another one I'm missing... I apologize in advance... is this feature already active in version 0.1.4? I can find my sessions/groups saved as bookmarks.

**Comment by Emano-Waldeck** [comment]
not bookmarks format per se, but the extension can now import and export as JSON. Use the right-click context menu over the toolbar button.

**Comment by EstherMoellman** [comment]
Thank you @Emano-Waldeck !
I can see now I wasn't clear at my request. Sorry for that.

By converting sessions into bookmarks I meant to save SaveTabs' (ST) sessions at Firefox' library. If you can build this feature, it'll be incredibly useful, because users will be able to open FF' library (Ctrl+Shift+H) or bookmarks in the SideBar, and from there users will be able to directly edit sessions (copy, paste, delete, move tabs etc).

Your JSON export function is useful for backup (thank you again).
But if you can put a copy of the sessions at the FF' bookmarks library, this will be more powerful than just backuping the JSON file, because this will create the complete tab session/group editing function for your ST' add-on.

Also in the future and as a second stage, if you can put sessions/groups inside bookmarks (SideBar), this will allow your ST to have a specific menu in the SideBar, creating the possibility of managing sessions/groups directly from the SideBar, better known as "Vertical Tab" management.

**Comment by Emano-Waldeck** [comment]
It is possible to use bookmarks however there is no place to save tabs properties other than titles and URLs, anyhow at this point using a new API is out of my focus. Instead, I added a simplified manager view. Give the latest commit a try and let me know if the new manager window works for you or not. You can rename, change orders and delete tabs. I might add creating new items later.

Also, since this extension is now mobile-friendly, it supports the sidebar view.

**Comment by EstherMoellman** [comment]
I apologize in advance because I’m not sure I was capable to make work this your new “manager view”. Firstly and sorry for my silly question, just to be sure that we’re in the same page: Where exactly is your “manager view”?

What I found is: mouse-click on Save-Tabs’ (ST) icon (open pop up) => mouse-click on “Preview this Session” => from there I was able to edit tabs. But it was a very limited editing function capability, only in the selected session, not across sessions. Again, I’m not sure if this is your “manager view”.

In case this really is your “manager view”, if you (please) can add some modifications, it’ll be possible to be used as a bookmark editor:
a) Instead editing tabs inside the small icon pop up window, IMO opening a new tab (in current window) and showing all the sessions/tabs to be edited, it’ll be much better.
b) IMO the “cancel & save” buttons are not needed. Changes should be automatically saved.
c) Cross edition capabilities between sessions is needed.
d) IMO the option of APPEND, OVERWRITE, IMPORT, EXPORT etc json files, should be included in this “manager view” tab, everything in one place and with easy access.
The logic of my suggestions above is based on current Firefox’ bookmark window. If you don’t want or can’t include ST’ sessions inside Firefox’ bookmarks, don’t worry!, this is not a must. You can perfectly have a ST “manager view”, if your add-on can open a new tab showing all sessions/tabs, and allowing edition.

Now, with regards to ST at SideBar, please it’ll be nice if you can collapse the sessions, allowing access to tabs, and also allowing edition capabilities (copy, paste, remove, move etc across sessions).

PS: Sorry, I couldn’t make work “APPEND” and “OVERWRITE” functions. A small window opens when I mouse-click these options, but everything behaves strangely, I can’t drop files etc. And I couldn’t make work the EXPORT function, I mouse-click the option and nothing happens.
